#!/bin/bash

# remove old repo
rm -rf CDN

# clone new repo
git clone https://github.com/soelgary/CDN.git CDN && cd CDN

# Update script permissions
chmod +x ./httpserver
chmod +x ./dnsserver

# install http dependencies
cd ./http && npm install