#!/bin/bash
port=  origin=  name= username= keyfile=

# list of hosts
HOSTS="ec2-54-174-6-90.compute-1.amazonaws.com ec2-54-174-6-90.compute-1.amazonaws.com"

while getopts "u:i:" opt; do
  case $opt in
  p)
      port=$OPTARG
      ;;
  o)
      origin=$OPTARG
      ;;
  n)
      name=$OPTARG
      ;;
  u)
      username=$OPTARG
      ;;
  i)
      keyfile=$OPTARG
      ;;
  esac
done

for host in $HOSTS
do
  ssh -i ${keyfile} ${username}@${host} "bash -s" -- < ./scripts/deploy
done