#!/bin/bash
port=  origin=  name= username= keyfile=

while getopts "u:i:n:" opt; do
  case $opt in
  p)
      port=$OPTARG
      ;;
  o)
      origin=$OPTARG
      ;;
  n)
      name=$OPTARG
      ;;
  u)
      username=$OPTARG
      ;;
  i)
      keyfile=$OPTARG
      ;;
  esac
done

echo "$username"
echo "$name"
echo "$keyfile"

ssh -i ${keyfile} ${username}@${name} "bash -s" -- < ./scripts/deploy