#!/bin/bash

# kill server
killall python > /dev/null 2>&1

# remove old repo
rm -rf CDN

# clone new repo
git clone https://github.com/soelgary/CDN.git CDN && cd CDN

# Update script permissions
chmod +x ./dnsserver