#!/bin/bash
port=  origin=  name= username= keyfile=

while getopts p:o:n:u:i opt; do
  case $opt in
  p)
      port=$OPTARG
      ;;
  o)
      origin=$OPTARG
      ;;
  n)
      name=$OPTARG
      ;;
  u)
      username=$OPTARG
      ;;
  i)
      keyfile=$OPTARG
      ;;
  esac
done

shift $((OPTIND - 1))

# remove old repo
rm -rf CDN

# clone new repo
git clone https://github.com/soelgary/CDN.git CDN && cd CDN

# run Make
make default

# install http dependencies
make http-server